name: Validate Compose & Shell
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose config
        run: docker compose config
      - name: Shellcheck scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./scripts
