name: Validate Compose & Shell

on:
  push:
    paths:
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/validate.yml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Make sure Compose v2 exists on the runner
      - name: Ensure Docker Compose v2
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: |
          if ! docker compose version >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
          fi

      - name: Docker Compose config
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: docker compose config

      # Lint any shell scripts if the folder exists
      - name: Install ShellCheck
        if: ${{ hashFiles('scripts/**') != '' }}
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: ShellCheck scripts
        if: ${{ hashFiles('scripts/**') != '' }}
        run: shellcheck -S warning scripts/*.sh || true
